FROM ubuntu:20.04
MAINTAINER DGrossnickle dgrossnickle@gmail.com 815-236-5309

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y curl apt-utils apt-transport-https debconf-utils gcc build-essential \
    && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && apt-get install -y python3-pip python3-dev python3-tk libpcre3-dev libz-dev \
    && cd /usr/local/bin \
    && ln -s /usr/bin/python3 python \
    && pip3 install --upgrade pip

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

EXPOSE 8000
WORKDIR /app
COPY . /app
CMD ["uwsgi", "--ini", "wsgi_config.ini"]